matrip-project/matrip-web

src/App.tsx, src/components/BottomNav/index.tsx, src/styles/GlobalStyles.tsx, src/styles/theme/style.d.ts, src/styles/theme/theme.ts, src/utils/colorUtils.ts
${getColor('black')} 이런 식으로 사용
_BottomNav/index.tsx 참고_
=> feat: theme 색상 선언

src/components/@atoms/Text.tsx, src/pages/Home/homeStyle.tsx, src/pages/Home/index.tsx
타입과 색상을 지정해서 사용
색상 디폴트: 'black'
Home/index.tsx
```
<Text type='headline2' color='neutral5'>마음에 맞는 사람들과</Text>
```
=> feat: text 컴포넌트 제작

src/App.tsx, src/components/@atoms/Collapsible.tsx, src/pages/Home/index.tsx, src/pages/NoticeBoard/index.tsx, src/utils/dateToString.ts
1. 공지사항 페이지가 추가되었습니다.
2. 텍스트 토글 버튼 및 컴포넌트가 추가되었습니다 (Collapsible.tsx)
3. util 함수에 Date 포멧을 string 으로 변환하는 함수가 추가되었습니다.
=> feat : 공지사항 페이지 및 텍스트 토글 컴포넌트 제작

src/App.tsx, src/components/@atoms/Collapsible.tsx, src/components/@atoms/Text.tsx, src/pages/FAQ/index.tsx, src/styles/theme/theme.ts
Collapsible, 색상 약간 수정
Text type추가 및 수정
=> feat: 고객센터 페이지 퍼블리싱

src/App.tsx, src/components/@atoms/Collapsible.tsx, src/components/@atoms/Text.tsx, src/pages/FAQ/index.tsx, src/pages/Home/index.tsx, src/styles/GlobalStyles.tsx, src/styles/theme/style.d.ts, src/styles/theme/theme.ts
기존의 텍스트 컴포넌트 방식에서 theme에 선언한 타입들을 가져와서 사용하는 방식으로 수정했습니다.
(텍스트 타입들은 피그마 font guide를 참고했습니다.)
색상들도 피그마 참고해서 수정했습니다.
폰트 사이즈 1rem=10px이 되도록 수정했습니다.
=> MT-31 텍스트 및 색상 타입 선언

src/components/@atoms/InterestButton.tsx, src/pages/Home/index.tsx
1. 관심사 버튼이 없어짐에 따라 여행지 선택 버튼으로 바꿨습니다 (동행만들기 페이지)
2. primary를 기본값으로 뒀구요 버튼을 클릭시 디자인이 바뀌는 건 secondary값일 때 입니다! - 이렇게 하는게 맞는지는 잘 모르겠는데 피드백 부탁드립니다 ㅎㅎ..
=> MT-57 기존 관심사 버튼을 여행지 선택 버튼으로 변경

src/App.tsx, src/components/@atoms/TabMenu.tsx, src/components/@atoms/Thumbnail.tsx, src/components/BottomNav/index.tsx, src/components/Map/index.tsx, src/pages/Detail/detailComponents/Info.tsx, src/pages/Detail/detailComponents/Plan.tsx, src/pages/Detail/detailStyle.tsx, src/pages/Detail/index.tsx, src/pages/ItineraryInfo/index.tsx
데이터는 피그마 토대로 임의로 만들어서 퍼블리싱 했습니다.
실제 api 연결하면서 수정될 부분이 있을 것 같습니다.
iterinaryInfo 폴더 안에 있던 지도 컴포넌트를 공통 컴포넌트로 옮겼습니다.
=> MT-61 여정 상세페이지 퍼블리싱

src/components/SnsConnect/index.tsx, src/pages/EditProfile/index.tsx
- 소셜 input 필드 추가 및 삭제 기능 추가
- 사진 추가 영역 추가 (로직 논의 팔요)
=> feat/소셜 추가 섹션, 이미지 추가 퍼블리싱

src/components/BottomNav/index.tsx, src/pages/EditProfile/index.tsx, src/pages/MyPageMain/index.tsx, src/pages/Profile/index.tsx
- 마이페이지 헤더 추가
- 마이페이지 바텀nav에 연결
=> feat: 헤더 추가 및 마이페이지 연결

src/App.tsx, src/components/@atoms/Button.tsx, src/components/Header/index.tsx, src/pages/MyPageMain/index.tsx, src/pages/Profile/index.tsx, src/pages/ResetPassword/index.tsx
- 비밀번호 찾기 페이지가 추가되었습니다
- 헤더로 인해 컴포넌트가 가려지는 문제를 해결했습니다.
=> feat/비밀번호 재설정 페이지,  헤더 수정

src/apis/loginApi.ts, src/pages/Login/index.tsx
=> feat: 로그인 api 연동

src/apis/api/journey.ts, src/pages/Detail/detailComponents/Info.tsx, src/pages/Detail/detailStyle.tsx, src/pages/Detail/index.tsx, src/pages/MapSearch/index.tsx, src/pages/MapSearch/mapPageStyle.tsx, src/pages/MapSearch/mapSearchComponents/GoogleMap.tsx, src/pages/MapSearch/mapSearchComponents/geocode.ts, src/pages/Posting/index.tsx, src/pages/Posting/postingComponents/ImageUpload.tsx, src/styles/GlobalStyles.tsx, src/types/postData.d.ts
- 게시물 등록 api 연결했습니다.
- 위치는 아직 선택하지 못합니다.
- 유저 아이디를 받아오는 로직은 아직 구현되지 않아서 임의로 1번 아이디 사용했습니다.
- Mainbox 스타일을 화면 너비가 390px 이하면 width: 100%가 되도록 수정했습니다.
=> MT-112 게시물 등록 api 연결

src/pages/MapSearch/mapPageStyle.tsx, src/pages/MapSearch/mapSearchComponents/GoogleMap.tsx, src/pages/Posting/index.tsx, src/pages/Posting/postingComponents/LocationSelect.tsx, src/redux/modules/locationSlice.tsx, src/redux/store.ts
- 리덕스 툴킷을 이용해 위도와 경도를 저장하도록 했습니다.
=> MT-97 위치 설정 기능 구현

src/components/Search/SearchStyle.tsx, src/components/UserList/index.tsx, src/components/UserList/userListStyle.tsx, src/pages/Detail/detailComponents/Info.tsx, src/pages/Detail/detailStyle.tsx, src/pages/Detail/index.tsx, src/pages/Home/homeStyle.tsx, src/pages/Home/index.tsx, src/pages/Posting/index.tsx, src/styles/GlobalStyles.tsx
- 너비가 390px보다 작은 화면에서도 중앙 정렬 되도록 수정했습니다.
=> MT-116 메인페이지 반응형으로 수정

src/apis/services/comment.ts, src/components/@atoms/CommentCount.tsx, src/components/@atoms/CommentInput.tsx, src/components/Map/index.tsx, src/hooks/useUserId.ts, src/pages/Comments/commentsCoponents/CommentBox.tsx, src/pages/Comments/index.tsx, src/pages/Detail/index.tsx, src/pages/Home/homeStyle.tsx, src/pages/Home/index.tsx, src/pages/Login/index.tsx, src/pages/MapSearch/index.tsx, src/pages/MapSearch/mapSearchComponents/GoogleMap.tsx, src/pages/MyPageMain/index.tsx, src/pages/Posting/index.tsx, src/pages/Posting/postingComponents/ImageUpload.tsx, src/redux/modules/postSlice.tsx, src/redux/modules/replySlice.tsx, src/styles/GlobalStyles.tsx, src/types/commentData.ts
- 댓글 목록에서 답글이면 답글 디자인으로 뜨도록 수정했습니다.
- 답글일 때 부모 댓글 밑으로 배치되도록 했습니다.
- 새 게시글 작성임에도 전에 수정했던 글의 데이터가 불러와지는 오류를 수정했습니다.
- 임의로 유저아이디 1번 사용했던 코드들 세션에서 받아오도록 수정했습니다.
- 세션에서 유저아이디 받아오는 로직 훅으로 분리했습니다. (있으면 number 타입으로 반환, 없으면 0)
=> MT-122 답글 표시, 새 게시글 작성 오류 수정

src/apis/api/editProfile.ts, src/apis/api/userData.ts, src/components/ImageCarousel/index.tsx, src/pages/EditProfile/index.tsx, src/pages/Login/index.tsx, src/pages/Profile/index.tsx, src/pages/ProfileViewer/index.tsx, src/redux/modules/userDataSlice.ts, src/storage/fetchUserDataWithSessionStorage.ts
=> feat: 이미지 추가 및 삭제

src/apis/api/editProfile.ts, src/components/SnsConnect/index.tsx, src/pages/EditProfile/index.tsx, src/utils/uploadImage.ts
=> feat/sns추가 및 삭제

src/App.tsx, src/components/@atoms/TabMenu.tsx, src/components/HeaderLogo/index.tsx, src/components/PostListScroll/index.tsx, src/components/PostListScroll/postListScrollStyle.tsx, src/components/Search/SearchStyle.tsx, src/components/SelectButton/index.tsx, src/pages/CompanionList/CompanionListStyle.tsx, src/pages/CompanionList/index.tsx, src/pages/Detail/detailComponents/Plan.tsx, src/pages/Home/homeStyle.tsx, src/pages/Home/index.tsx, src/pages/MyInterestedCompanionLog/index.tsx, src/pages/MyInterestedCompanionLog/myCompanionLogStyle.tsx, src/pages/MyPostWrote/myPostWroteStyle.tsx, src/pages/PopularTravel/index.tsx, src/pages/Profile/index.tsx
- 날짜 필터 색상 변경했습니다.
- 메인, 동행리스트, 인기여행지 상하단 여백 수정했습니다.
- 관심 동행 목록, 내가 쓴 글의 헤더를 변경했습니다.
- 관심 동행 목록, 내가 쓴 글의 경로를 좀 더 간단하게 변경했습니다.
- 게시글 없음 문구 위치를 조정했습니다.
=> MT-129 여백, 색상 등 변경

src/components/BottomNav/index.tsx, src/components/PostListScroll/index.tsx, src/components/Search/index.tsx, src/components/UserList/index.tsx, src/pages/Home/index.tsx
=> fix: 검색 후 하단 탭 표시 오류 수정

src/apis/api/journey.ts, src/components/BottomNav/index.tsx, src/components/PostListScroll/index.tsx, src/components/SelectButton/index.tsx, src/pages/Posting/index.tsx, src/redux/modules/searchSlice.tsx
- 필터링 api 연결했습니다.
- 지역 필터 추가했습니다.
- 글 등록 후 해당 글으로 연결되도록 변경했습니다.
- 모집 상태 수정 오류를 고쳤습니다.
=> refactor: 필터 관련 리팩토링

src/components/DatePick/index.tsx, src/components/SelectButton/index.tsx, src/pages/Home/index.tsx, src/pages/Posting/postingComponents/DateSelect.tsx
- 필터링과 글 작성할 때 쓰이는 달력을 DatePick 컴포넌트로 분리했습니다.
- 디자인을 참고해 수정했습니다.
=> refactor: 날짜 선택 컴포넌트화 및 커스텀

src/apis/api/journey.ts, src/components/PostListScroll/index.tsx, src/components/SelectButton/index.tsx, src/redux/modules/searchSlice.tsx
=> fix: 필터링 오류 해결
